# Script taken from Nat Tuck nu_mart project
language: elixir
elixir:
  - 1.5.2
otp_release:
  - 20.1
before_script:
  - psql -U postgres -c "CREATE USER microblog WITH PASSWORD 'pieW1keiwe';"
  - psql -U postgres -c "CREATE DATABASE microblog_test;"
